#!/bin/bash

alias notes="vimx -u ~/data/dotfiles/vimrc/modes/wiki.vimrc"
alias ronotes="vimx -R -u ~/data/dotfiles/vimrc/modes/wiki.vimrc"

alias vim="_install_nvm && vimx"
alias vimv="vimx -u ~/data/dotfiles/vimrc/vanilla/common.vimrc"
alias vimuml="vimx -u ~/data/dotfiles/vimrc/modes/plantuml.vimrc"
alias vimlatex="_install_nvm && vimx -u ~/data/dotfiles/vimrc/modes/latex.vimrc"
alias vimmd="vimx -u ~/data/dotfiles/vimrc/modes/markdown.vimrc"

alias vimpy="vimx \`mktemp\`.py"
alias vimkts="vimx \`mktemp -u\`.kts"
alias vimclj="vimx \`mktemp -u\`.clj"
alias nvimpy="nvim \`mktemp\`.py"
alias nvimkts="nvim \`mktemp -u\`.kts"
alias nvimclj="nvim \`mktemp -u\`.clj"

alias nvimtex="nvim -u ~/data/dotfiles/nvim/modes/tex.vim"
alias nvimmd="nvim -u ~/data/dotfiles/nvim/modes/markdown.vim"

alias vim_light="echo light > ~/._background"
alias vim_dark="echo dark > ~/._background"

# Backgroun env var for vim
if [[ -a ~/._background ]]; then
  export BACKGROUND=$(cat ~/._background)
else
  export BACKGROUND=dark
fi

if [[ "$BACKGROUND" == 'light' ]]; then
  export LS_COLORS=${LS_COLORS}:'ln=7;35'
fi

alias watch="watch "

# Custom aliases
# Kubernetes
alias kapp="kubectl apply -f"
alias kgp="kubectl get pods"
alias kdel="kubectl delete"
alias kds="kubectl delete service"
alias kdd="kubectl delete deployment"
alias kl="kubectl logs"
alias klf="kubectl logs -f"
alias kdesp="kubectl describe pod"
alias kdesd="kubectl describe deployment"
alias kdess="kubectl describe service"


function _install_nvm() {
  # NVM settings
  export NVM_DIR="$HOME/.config/nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

#
# Not to be disturbed by Ctrl-S ctrl-Q in terminals:
stty -ixon

