#!/bin/bash

export INSTALL_DIR=/usr/local/software
export INSTALL_BIN=${INSTALL_DIR}/bin
export SDKMAN_CANDIDATES=${HOME}/.sdkman/candidates

export LOMBOK_PATH=${HOME}/bin/lombok.jar
export JAVA_HOME=${SDKMAN_CANDIDATES}/java/current
export MAVEN_HOME=${SDKMAN_CANDIDATES}/maven/current
export GRADLE_HOME=${SDKMAN_CANDIDATES}/gradle/current
export HISTCONTROL=ignoredups:erasedups
export XDG_CONFIG_HOME=${HOME}/.config

export PATH="\
${HOME}/.local/bin:\
${HOME}/bin:\
/usr/local/software/bin:\
${JAVA_HOME}/bin:\
${MAVEN_HOME}/bin:\
${GRADLE_HOME}/bin:\
${PATH}"

