#!/bin/bash

export INSTALL_DIR=/usr/local/software
export INSTALL_BIN=${INSTALL_DIR}/bin

export LOMBOK_PATH=${HOME}/bin/lombok.jar
export JAVA_HOME=/usr/lib/jvm/java-openjdk
export MAVEN_HOME=${INSTALL_DIR}/apache-maven-3.8.6
export HISTCONTROL=ignoredups:erasedups
export XDG_CONFIG_HOME=${HOME}/.config

export PATH="\
${HOME}/.local/bin:\
${HOME}/bin:\
/usr/local/software/bin:\
${JAVA_HOME}/bin:\
${MAVEN_HOME}/bin:\
${PATH}"

